name: Deploy to Production

on:
  workflow_dispatch:

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci
          
      - name: Build
        run: npm run build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.SERVER_USERNAME }}
      HOST: ${{ secrets.SERVER_HOST }}

    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
      
      - name: Deploy to Web Server
        run: rsync -avz --delete -e "ssh -o StrictHostKeyChecking=accept-new" $GITHUB_WORKSPACE/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USERNAME }}/public_html
