name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Corrected to use the correct Node.js version

      - name: Install and Build
        run: |
          npm ci
          npm test
          npm run build